#!/usr/bin/env bash
# inject-contact.sh — 联系方式卡片注入器（单一真实源）
#
# 把 docs/_snippets/contact.html 的内容注入到文章占位符中。
# 占位符: <!-- CONTACT-START --> ... <!-- CONTACT-END -->
# 可重入(幂等): 已有占位符则原地替换中间内容; 没有占位符则在文件末尾追加。
# 改联系方式只需改 docs/_snippets/contact.html, 再跑本脚本即可全量同步。
#
# Usage:
#   ./scripts/inject-contact.sh              # 注入 docs 下所有内容文章(排除 README.md)
#   ./scripts/inject-contact.sh <file...>    # 只处理指定文件(用于测试/局部刷新)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

SNIPPET="docs/_snippets/contact.html"
START="<!-- CONTACT-START -->"
END="<!-- CONTACT-END -->"
NOTE="<!-- Auto-generated by scripts/inject-contact.sh — 单一真实源: ${SNIPPET} -->"

[ -f "$SNIPPET" ] || { echo "ERROR: snippet not found: $SNIPPET"; exit 1; }

if [ $# -gt 0 ]; then
    FILES=("$@")
else
    FILES=()
    while IFS= read -r -d '' f; do
        FILES+=("$f")
    done < <(find docs -name '*.md' -type f ! -name 'README.md' -print0)
fi

injected=0
updated=0

for f in "${FILES[@]}"; do
    [ -f "$f" ] || { echo "WARN: not a file: $f"; continue; }

    if grep -qF "$START" "$f"; then
        # 原地替换占位符块内容(保留卡片在文件中的位置)
        tmp="$(mktemp)"
        awk -v START="$START" -v ENDMARK="$END" -v NOTE="$NOTE" -v SNIPPET="$SNIPPET" '
            BEGIN { skip=0 }
            $0==START {
                print START; print NOTE
                while ((getline line < SNIPPET) > 0) print line
                close(SNIPPET)
                print ENDMARK
                skip=1; next
            }
            $0==ENDMARK { skip=0; next }
            skip { next }
            { print }
        ' "$f" > "$tmp"
        mv "$tmp" "$f"
        updated=$((updated+1))
    else
        # 文件末尾追加新块(先补空行分隔)
        {
            printf '\n%s\n' "$START"
            printf '%s\n' "$NOTE"
            cat "$SNIPPET"
            printf '%s\n' "$END"
        } >> "$f"
        injected=$((injected+1))
    fi
done

echo "✅ contact 注入完成: 新增 ${injected}, 更新 ${updated} (共处理 ${#FILES[@]} 个文件)"
echo "   改联系方式请编辑: ${SNIPPET}  →  再跑: ./scripts/inject-contact.sh"
