#!/usr/bin/env bash
# inject-contact.sh — 联系方式卡片注入器（单一真实源）
#
# 2026-07 起：联系方式卡片只在 README 保留，不再注入内容文章。
# 本脚本不再扫描全量内容文章；只用于显式刷新指定 README 的卡片。
# 占位符: <!-- CONTACT-START --> ... <!-- CONTACT-END -->
# 可重入(幂等):
#   - 已有占位符: 原地替换块内容(保留卡片在文件中的位置)。
#   - 无占位符: 在文件开头插入新块。
#   - 重复运行: 结果完全一致, 不会堆叠。
# 根 README.md 的卡片放在 banner 之后(非顶部), 用占位符标记;
# 显式对该文件运行脚本会原地更新, 不会移动位置。
# 改联系方式只需改 docs/_snippets/contact.html, 再对需要刷新的 README 显式跑本脚本。
#
# Usage:
#   ./scripts/inject-contact.sh                                    # 已禁用全量注入，仅打印提示
#   ./scripts/inject-contact.sh README.md docs/.../README.md ...   # 刷新指定 README 的卡片

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

SNIPPET="docs/_snippets/contact.html"
START="<!-- CONTACT-START -->"
END="<!-- CONTACT-END -->"
NOTE="<!-- Auto-generated by scripts/inject-contact.sh — 单一真实源: ${SNIPPET} -->"

[ -f "$SNIPPET" ] || { echo "ERROR: snippet not found: $SNIPPET"; exit 1; }

if [ $# -gt 0 ]; then
    FILES=("$@")
else
    # 2026-07 起：内容文章不再注入卡片，全量注入已禁用。
    # 如需刷新某个 README 的卡片，请显式传文件，例如：
    #   ./scripts/inject-contact.sh README.md docs/evaluation/README.md
    echo "ℹ️ 内容文章不再注入联系方式卡片（仅 README 保留）。"
    echo "   刷新 README 卡片请显式传文件，例如："
    echo "   ./scripts/inject-contact.sh README.md docs/evaluation/README.md"
    exit 0
fi

injected=0
updated=0

for f in "${FILES[@]}"; do
    [ -f "$f" ] || { echo "WARN: not a file: $f"; continue; }

    if grep -qF "$START" "$f"; then
        # 已有占位符: 原地替换块内容(保留卡片在文件中的位置)
        tmp="$(mktemp)"
        awk -v START="$START" -v ENDMARK="$END" -v NOTE="$NOTE" -v SNIPPET="$SNIPPET" '
            BEGIN { skip=0 }
            $0==START {
                print START; print NOTE
                while ((getline line < SNIPPET) > 0) print line
                close(SNIPPET)
                print ENDMARK
                skip=1; next
            }
            $0==ENDMARK { skip=0; next }
            skip { next }
            { print }
        ' "$f" > "$tmp"
        mv "$tmp" "$f"
        updated=$((updated+1))
    else
        # 无占位符: 在文件开头插入新块(正文去首尾多余空行)
        body="$(awk -v START="$START" -v ENDMARK="$END" '
            BEGIN { skip=0 }
            $0==START { skip=1; next }
            $0==ENDMARK { skip=0; next }
            skip { next }
            { print }
        ' "$f")"
        {
            printf '%s\n' "$START"
            printf '%s\n' "$NOTE"
            cat "$SNIPPET"
            printf '%s\n\n' "$END"
            printf '%s' "$body" | awk '{ a[NR]=$0 } END { s=1; while (s<=NR && a[s]~/^[ \t]*$/) s++; e=NR; while (e>=s && a[e]~/^[ \t]*$/) e--; for (i=s;i<=e;i++) print a[i] }'
        } > "$f"
        injected=$((injected+1))
    fi
done

echo "✅ contact 注入完成: 新增 ${injected}, 更新 ${updated} (共处理 ${#FILES[@]} 个文件)"
echo "   改联系方式请编辑: ${SNIPPET}  →  再跑: ./scripts/inject-contact.sh <README 文件...>"
